print("Введіть свої дані") #Ввід даних
firstname = input("Ваше ім'я: ")
secondname = input("Ваше прізвище: ")
number = input("Ваш номер телефону: ")
country = input("Країна в якій проживаєте: ")
city = input("Місто в якому проживаєте: ")
index = input("Почтовий індекс міста: ")
street = input("Назва вашої вулиці: ")
house = input("Номер вашого будинку: ")
ap = input("Номер вашої квартири: ")
print("Впишіть будь-що щоб вивести уведені дані")
continue1 = input()
print(firstname, secondname) #Вивід даних
print()
print(number)
print()                                          
print(f"Str.{street} {house}, ap{ap}, {city}")
print()
print(index)
print()
print(city)